### PR TITLE
Colabs and nmrglue

### PR DESCRIPTION
**Pull request by Darren01**
Tutorial introduction rst file modified to include instructions to download nmrglue to colabs.

A first step to being used on that platform.

### CODE REVIEW

**Comment by kaustubhmote** [comment]
@Darren01 This looks like it will be very useful. Thanks for the contribution.

I notice that you are downloading nmrglue and installing it from source. Is there some reason something like `! python -m pip install nmrglue` (or even `! python -m pip install git+https://github.com/jjhelmus/nmrglue` if you want the latest features) does not work for you on Colabs? (It does seem to work fine with my instance). I think the current lines 548-590 should be replaced by installing this via pip, which is also the recommended way to install nmrglue. This also has the side effect of not pinning the documentation to a particular version of nmrglue (0.7 in your case). Lines starting from `! wget` can remain as they are, the tutorial file will simply get extracted in the home folder and can be used directly from there. I'll be happy to merge this if you can confirm that the above suggestions work for you, and change the necessary lines (unless, of course, there is some other reason why you chose to install from source).

One side note: Currently the nmrglue documentation has not been updated in quite some time, and I cant even seem to build the HTML with the latest Sphinx version. So even after merging, the readthedocs website may not get updated immediately. I am working on fixing this in a branch on my [fork](https://github.com/kaustubhmote/nmrglue/tree/documentation), but this may take a bit of time.

**Comment by Darren01** [comment]
The code `! python -m pip install git+https://github.com/jjhelmus/nmrglue` worked when it replaced the code 
`#!wget -q https://github.com/jjhelmus/nmrglue/releases/download/v0.7/nmrglue-0.7.tar.gz`.

I also hashed out

`#!tar -xzf nmrglue-0.7.tar.gz
#import os
#os.chdir('nmrglue-0.7')
#!python setup.py install`

but kept everything else.  I didn't have any problems running it.  (It didn't have the latency problems that I had in past attempts which was an improvement.  As to why I didn't do this in the first place?).

**Comment by kaustubhmote** [comment]
That sounds great. I would also suggest removing the lines instead of commenting them out in the final version. Just push the changes here and I can merge them in.

**Comment by Darren01** [comment]
Code modified such that it installs to Colabs using pip with other slight amendments to make it tidier, eg hashed out lines removed.

**Pull request merged**
