### PR TITLE
PY3: changes not suggested by pyupgrade

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**

### CODE REVIEW

**Comment by jjhelmus** [comment]
LGTM

**Comment by kaustubhmote** [comment]
This merge may need to be partially reverted. xcpy module works within Topspin  with Jython rather than CPython, which is why the antiquated style/features of Python 2.7 is used everywhere.

**Comment by DimitriPapadopoulos** [comment]
I just discovered that [Jython](https://www.jython.org/) only supports Python 2. Given the pace of change of Python libraries, I guess this means Jython is more or less dead. Any way, since the xcpy module works within TopSpin which includes Jython. I will revert `xcpy.py` changes. Also `xcpy_test.py` changes?

**Comment by DimitriPapadopoulos** [comment]
BTW, I got confused by `setup.py`:
```
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
```

**Comment by DimitriPapadopoulos** [comment]
Reverted in #183.

**Pull request merged**
