### PR TITLE
Add test and docs for fileio.spinsolve

### PR DESCRIPTION
**Pull request by dcambie**
Few improvements to the spinsolve import module

* minor change to acqu.par parsing, e.g. now `["Sample"] == "EtOH"` before it was  `["Sample"] == "\"EtOH\""` (with additional quote marks)
* Added info to docs
* Tests added (the spectrum referenced in the test has not been added as the `/data/` folder is in .gitignore, where can I put it? Also, how to run the tests for the other modules (e.g. bruker)?

### CODE REVIEW

**Comment by dcambie** [comment]
Ops, sorry I realized only now that the project still supports Python2. By seeing only py3.6 listed in setup.py I assumed it was fine to use pathlib and f-strings. I will revert those changes, sorry for the confusion

**Comment by dcambie** [comment]
> 
> 
> Ops, sorry I realized only now that the project still supports Python2. By seeing only py3.6 listed in setup.py I assumed it was fine to use pathlib and f-strings. I will revert those changes, sorry for the confusion

Should be fine now

**Comment by kaustubhmote** [comment]
Thanks, @dcambie. I will go through this in a few days and merge this in.

**Comment by kaustubhmote** [comment]
Sorry, this took so long. All the changes look good to me, except that I don't have the data to test. Can you attach it here? We can put it in later in the repository

**Comment by LCageman** [comment]
Thanks for your code, @dcambie!
I have one suggestion, the function you added, "parse_spinsolve_acqu_line(line)", can also be used for the proc.par file. This file is only generated when using the spinsolve expert software, but the syntax is the same. Therefore I suggest to rename it to "parse_spinsolve_par_line" (or something like that) and use it for both acqu.par and proc.par.

I also attached two spectra, one (carbon spectrum) from the normal spinsolve and one from the expert software.
[Data Examples.zip](https://github.com/jjhelmus/nmrglue/files/7083773/Data.Examples.zip)

**Comment by LCageman** [comment]
Don't forget to rename it in the docs as well:
doc/source/reference/spinsolve.rst

(I'd do it myself, but can't find any option in the browser to edit it)

**Comment by dcambie** [comment]
Umh, I used the IDE refactoring tool and enabled lookup in non-code part of the project so that changed also `doc/source/reference/spinsolve.rst` . I guess that should be ok or did I miss something?

**Comment by LCageman** [comment]
My bad, I guess I looked at the wrong place. Have a nice evening!

**Pull request merged**
