### PR TITLE
Automatic phase correction

### PR DESCRIPTION
**Pull request by mfitzp**
An initial implementation of automatic phase correction for consideration.
This adds a new function to `proc_base` of `autops`, alongside two example
phase optimisation (scoring) algorithms: ACME and a naive peak minima approach.

Standard algorithms can be selected by name ('acme', 'peak_minima') while
custom algorithms can be provided as a function.

A [demo notebook is available](https://github.com/mfitzp/ipython-notebooks/blob/master/public/Automatic%20phase%20correction%20of%20NMR%20spectra.ipynb).

### CODE REVIEW

**Comment by mfitzp** [comment]
Suggestions for improvements, additional algorithms to implement, etc. are most welcome.

**Comment by jjhelmus** [comment]
@mfitzp This is a great addition to nmrglue, thanks for making it available.  A few comments:

* Could these functions be move into a new file in the process directory, maybe proc_autophase.py?  I don't consider automatic phase to be a "basic" processing technique so I don't think it belongs in proc_base.py 

* The `ps_acme` and  `ps_peak_minima` function could have better names to reflect that they are calculating a score I think making them private would be prudent, _ps_acme_score and ps_peak_minima_score sound good to be.

* A few lines have some style issues.  nmrglue tried to follow [PEP8](https://www.python.org/dev/peps/pep-0008/) as much as possible.  Specifically lines 999 and 1000 are too long (79 character max), a few lines have extraneous whitespace and there is an extra blank line before the autops function.

* Do these functions work on two dimensional data?  If not this should be mentioned in the docstring.

**Comment by mfitzp** [comment]
@jjhelmus Thanks for the feedback (and apologies for the coveralls update spam; I got caught rebasing down to a single commit). In the update to the PR I've moved the autophase code into `proc_autophase` as `autops` and renamed the score functions as suggested `_ps_acme_score` etc.

I've fixed the PEP8 issues, though there is some white-space left in calculations for clarity.

At present the algorithms are only tested for 1D spectra but should be possible to adapt for 2D with some thought. Unfortunately I don't have any unphased 2D data (or any, actually) to test with. If you're able to provide some I'll see what I can do!

**Comment by jjhelmus** [comment]
@mfitzp There are a few examples of 2D data at the nmrglue [Google code download page](https://code.google.com/p/nmrglue/downloads/list?q=label:Example-Data) that could be used to develop a 2D version of the autophasing algorithm.  In particular the data from the [process_pipe_2d example](http://nmrglue.readthedocs.org/en/latest/examples/process_pipe_2d.html) might be a good choice.  

I merged in this branch as is, made some minor style changes and added the module to the documentation.  Feel free to open a new PR for the 2D work.  Thanks again for the contribution.

**Pull request merged**
